[package]
name = "pillar_model"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.13.0"
kmp = "0.1.1"
rand = "0.8.5"

[dev-dependencies]
bencher = "0.1.5"
test-case = "*"
bench = "1.1.0"

[[bench]]
name = "benching"
harness = false
